### ISSUE TITLE
v0.8.3 error 'No module named 'readline'

### ISSUE THREAD

**Issue by djbooth007** [TheR1D/shell_gpt#137] opened 2023-04-03 03:23 UTC
Using Windows with python3, after upgrading to v0.8.3 I got error 'No module named 'readline'.

Solved this issue by installing pyreadline3

`pip install pyreadline3`

**Comment by hongwen000** [comment] 2023-04-03 08:04
+1

**Comment by alexn-s** [comment] 2023-04-03 20:54
i just encountered the same issue. probably not for windows yet.

**Comment by Kreijstal** [comment] 2023-04-03 21:43
Thank you

**Comment by TheR1D** [comment] 2023-04-03 22:09
Based on my research, the readline module is pre-installed with Python on certain platforms, such as macOS and Linux. Nevertheless, it is not part of the Python standard library for Windows. Should be fixed in coming patches.

**Closed** 2023-04-07 18:30 UTC
Labels: bug

**Comment by LeartS** [comment] 2024-06-05 11:37
The problem is still present if installing `shell-gpt` on Linux (Ubuntu 24.04) using `pipx`, which installs it into its own separate virtualenvironment (similar to `npx`).

**Comment by tbal** [comment] 2025-11-27 10:20
Same problem still present with Pop!_OS (ubuntu 22.04 based) using `pipx` and latest `shell-gpt` 1.4.5. Would it cause harm to add readline as a dependency not only for windows?

**Comment by tbal** [comment] 2025-11-27 10:24
Workaround using `pipx` is to inject the missing dependency:
`pipx inject shell-gpt readline`
