### ISSUE TITLE
Set temperature/top-p values

### ISSUE THREAD

**Issue by johnd0e** [TheR1D/shell_gpt#458] opened 2024-01-28 22:26 UTC
As I found, altering values is possible only with commandline keys.

So I propose:
1. Config option for default values.
2. Roles options

**Comment by TheR1D** [comment] 2024-01-29 21:56
Closing this ticket as it is a duplicate of https://github.com/TheR1D/shell_gpt/issues/425. Please follow the discussion and further updates there. Thank you for your contribution.

**Closed by TheR1D** 2024-01-29 21:56 UTC
